environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TARGET: x86_64-pc-windows-msvc

install:
  # Prepend newly Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "pip install -r dev-requirements.txt"

  # Download and install rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin
  - rustc -V
  - cargo -V

build_script:
  - "python setup.py build"
  - "cargo build --manifest-path extensions/Cargo.toml --package cpython --verbose"
#   - "cargo build --manifest-path extensions/Cargo.toml --verbose"
  - "python setup.py build_rust"

# TODO(borispf)
test_script: off

after_test:
  - "python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
