environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TARGET: x86_64-pc-windows-msvc

install:
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - python --version

build: off

# TODO(borispf)
test_script: off

build_script:
 - "%PYTHON%\\python.exe setup.py build_py"
 - "%PYTHON%\\python.exe setup.py build_rust"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
