environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TARGET: x86_64-pc-windows-msvc

platform:
  - x64

install:
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - rustc -V
  - cargo -V
  - python --version

build: off

# TODO(borispf)
test_script: off

build_script:
 - "%PYTHON%\\python.exe setup.py build_py"
 - "set PATH=C:\Python27-x64;%PATH%&& cargo build --manifest-path extensions/Cargo.toml --verbose"
 - "%PYTHON%\\python.exe setup.py build_rust"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
